language: php

php:
  - 7.0
  - 7.1

before_install:
  - composer self-update

install:
  - composer install --quiet --no-interaction --prefer-dist
  - composer dumpautoload -o

script:
  - vendor/bin/phpunit